server:
  port: 8082

spring:
  application:
    name: secure-exam-portal-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD:"NO PASSWORD"}
    driver-class-name: ${DB_DRIVER}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - openid

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:secure-exam-portal}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:900}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:}

app:
  cors:
    front-end-url: ${FRONTEND_URL:http://localhost:5173}
  security:
    public-doc-enabled: ${PUBLIC_DOC_ENABLED:false}
  auth:
    role-bootstrap:
      admin-emails: ${ADMIN_EMAILS:}
      teacher-emails: ${TEACHER_EMAILS:}
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:http://localhost:5173/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:http://localhost:5173/oauth/failure}

springdoc:
  api-docs:
    enabled: ${PUBLIC_DOC_ENABLED:false}
  swagger-ui:
    enabled: ${PUBLIC_DOCS_ENABLED:false}
